main:
  - name: Malware Blog
    url: /malware-blog/
    weight: 1
  - name: Personal Blog
    url: /personal-blog/
    weight: 2
  - name: IOCs
    url: /iocs/
    weight: 3
  - name: Signatures
    url: https://github.com/c3rb3ru5d3d53c/signatures/
    weight: 4
  - name: Documents
    url: /docs/
    weight: 5
